import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendAlertEmail({
  to,
  subject,
  childName,
  alertType,
  message,
}: {
  to: string;
  subject: string;
  childName: string;
  alertType: string;
  message: string;
}) {
  return resend.emails.send({
    from: "Guardian AI <onboarding@resend.dev>",
    to,
    subject,
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f8fafc; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .header { background: linear-gradient(135deg, #0ea5e9, #6366f1); padding: 32px; color: white; }
            .header h1 { margin: 0; font-size: 24px; }
            .header p { margin: 8px 0 0; opacity: 0.9; }
            .content { padding: 32px; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
            .badge-vaccination { background: #dbeafe; color: #1d4ed8; }
            .badge-medication { background: #fef3c7; color: #92400e; }
            .badge-growth_anomaly { background: #fee2e2; color: #991b1b; }
            .badge-appointment { background: #d1fae5; color: #065f46; }
            .badge-ai_summary { background: #ede9fe; color: #5b21b6; }
            .message { margin: 16px 0; padding: 16px; background: #f8fafc; border-radius: 8px; line-height: 1.6; }
            .footer { padding: 24px 32px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Guardian AI</h1>
              <p>Health Alert for ${childName}</p>
            </div>
            <div class="content">
              <span class="badge badge-${alertType}">${alertType.replace("_", " ")}</span>
              <div class="message">${message}</div>
            </div>
            <div class="footer">
              <p>This is an automated alert from Guardian AI. Log in to your dashboard for more details.</p>
            </div>
          </div>
        </body>
      </html>
    `,
  });
}

export async function sendWeeklySummaryEmail({
  to,
  childName,
  summary,
  tip,
}: {
  to: string;
  childName: string;
  summary: string;
  tip: string;
}) {
  return resend.emails.send({
    from: "Guardian AI <onboarding@resend.dev>",
    to,
    subject: `Weekly Health Summary for ${childName}`,
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f8fafc; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .header { background: linear-gradient(135deg, #10b981, #0ea5e9); padding: 32px; color: white; }
            .header h1 { margin: 0; font-size: 24px; }
            .content { padding: 32px; }
            .summary { margin: 16px 0; padding: 16px; background: #f0fdf4; border-radius: 8px; border-left: 4px solid #10b981; line-height: 1.6; }
            .tip { margin: 16px 0; padding: 16px; background: #eff6ff; border-radius: 8px; border-left: 4px solid #3b82f6; }
            .tip-label { font-weight: 600; color: #1d4ed8; margin-bottom: 8px; }
            .footer { padding: 24px 32px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Weekly Health Summary</h1>
              <p>${childName}'s health overview</p>
            </div>
            <div class="content">
              <div class="summary">${summary}</div>
              <div class="tip">
                <div class="tip-label">Health Tip of the Week</div>
                ${tip}
              </div>
            </div>
            <div class="footer">
              <p>Generated by Guardian AI. View full details on your dashboard.</p>
            </div>
          </div>
        </body>
      </html>
    `,
  });
}
